[redis]
server_port = "127.0.0.1:6379"
password = "password"
database = 1
key_prefix = "port"
key_ttl = 9999
[api]
http_prefix = "/portmanager"
[app]
    [my_web_server]
    port = 30000
    [my_job_server]
    port = 30100
    # [...]